version: '3.8'

services:
  node:
    build:
      context: .
    container_name: node_postgresql_container
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    command: npm run dev
    volumes:
      - app_volume:/usr/src/app
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - C:/Aasif-Development-Workspace/local_pg_data:/var/lib/postgresql/data  # Local directory bind mount (Windows)
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  app_volume:
    driver: local
